#!/usr/bin/env python

import os
import pygments
from pygments.lexers import get_lexer_by_name
from pygments.formatters import HtmlFormatter

docFile = 'index.html'
css = HtmlFormatter().get_style_defs('.highlight')

with open( 'highlight.css', 'w' ) as f:
    f.write( css )

lexer = get_lexer_by_name("python", stripall=True)
formatter = HtmlFormatter(linenos=True, cssclass="source")

files = [ ]
for d, sd, fs in os.walk( '../tests/' ):
    for f in fs:
        if '.py' == f[-3:]:
            files.append( os.path.join( d, f ) )

pytext = [ ]
for f in files:
    with open( f, 'r' ) as _f:
        pytext.append( _f.read( ) ) 

headHtml = '<link rel="stylesheet" type="text/css" href="highlight.css" >'
headHtml += '<title>pypgfplots</title>';
text = [ '<!DOCTYPE html> <meta charset="utf-8"> ' ]
text += [ '<html> <head>%s</head> <body>' % headHtml ]

text += [ '''
<h1>pypgfplots</h1>
<p>
<a href="https://github.com/dilawar/pypgfplots">
<img src="" alt="GitHub Repository" data-canonical-src=""> 
</a>
</p> 

<p>PDFs are generated by running <tt>pdflatex</tt> on TeX files
produced by python script (on left). On right, are the PNGs generated from 
PDF by following command.
<pre>
convert -density 300 -quality 90 filename.pdf filename.png 
</pre>'''
    ]

text += [ '<h1>Examples</h1>' ]
text.append( "<table>" )
for f, ftext in zip( files, pytext ):
    fname = os.path.basename( f )
    imgname = fname + '.png'
    url = 'https://media.githubusercontent.com/media/dilawar/pypgfplots/master/docs/%s' % imgname 
    text.append( '<tr>' )
    text.append( '</td><td>' )
    code = pygments.highlight( ftext, lexer, formatter )
    text.append( '<div class="highlight" width="500px">{0}</div>'.format(code) )
    text.append( '</td><td>' )
    text.append( '<img src="{0}" width="500px">'.format(url) )
    text.append( '</td>' )
    text.append( '</tr>' )

text += [ "</table>" ]

text += [ '</body> </html>' ]

txt = '\n'.join( text )
with open( docFile, 'w' ) as f:
    print( txt )
    f.write( txt )

